version: '3.9'

name: gleam-backend-container

services:
  auth-api:
    container_name: gleam-auth-api
    build:
      context: .
      dockerfile: Dockerfile.auth
    ports:
      - "8081:1323"

  user-api:
    container_name: gleam-user-api
    build:
      context: .
      dockerfile: Dockerfile.user
    ports:
      - "8080:1324"
    depends_on:
      - user-db

  user-db:
    image: postgres
    container_name: user-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: user_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5