version: '3.9'

name: gleam-backend-container

services:
  user-db:
    image: postgres
    container_name: user-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: user_db

  group-db:
    image: postgres
    container_name: group-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: group_db

  auth-api:
    container_name: gleam-auth-api
    build:
      context: .
      dockerfile: Dockerfile.auth
    ports:
      - "9000:1323"

  user-api:
    container_name: gleam-user-api
    build:
      context: .
      dockerfile: Dockerfile.user
    ports:
      - "9001:1324"
    depends_on:
      - user-db

  group-api:
    container_name: gleam-group-api
    build:
      context: .
      dockerfile: Dockerfile.group
    ports:
      - "9002:1325"
    depends_on:
      - group-db
