// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package userdb

import (
	"database/sql"
)

type Friend struct {
	ID        int32          `json:"id"`
	UserId1   sql.NullInt32  `json:"user_id1"`
	UserId2   sql.NullInt32  `json:"user_id2"`
	Status    sql.NullString `json:"status"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type User struct {
	ID             int32        `json:"id"`
	Username       string       `json:"username"`
	Email          string       `json:"email"`
	Firstname      string       `json:"firstname"`
	Lastname       string       `json:"lastname"`
	PhoneNo        string       `json:"phone_no"`
	PrivateAccount bool         `json:"private_account"`
	CreatedAt      sql.NullTime `json:"created_at"`
}
