// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package groupdb

import (
	"database/sql"
	"time"
)

type Group struct {
	GroupID        int32          `json:"group_id"`
	GroupName      string         `json:"group_name"`
	GroupCreatorID int32          `json:"group_creator_id"`
	Description    sql.NullString `json:"description"`
	PhotoUrl       sql.NullString `json:"photo_url"`
	TagID          int32          `json:"tag_id"`
	Frequency      sql.NullInt32  `json:"frequency"`
	MaxMembers     int32          `json:"max_members"`
	GroupType      string         `json:"group_type"`
	Visibility     bool           `json:"visibility"`
	CreatedAt      time.Time      `json:"created_at"`
}

type GroupMember struct {
	GroupID   int32     `json:"group_id"`
	MemberID  int32     `json:"member_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type GroupRequest struct {
	GroupID     int32          `json:"group_id"`
	MemberID    int32          `json:"member_id"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Post struct {
	PostID      int32          `json:"post_id"`
	MemberID    int32          `json:"member_id"`
	GroupID     int32          `json:"group_id"`
	PhotoUrl    sql.NullString `json:"photo_url"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

type PostComment struct {
	CommentID int32     `json:"comment_id"`
	PostID    int32     `json:"post_id"`
	MemberID  int32     `json:"member_id"`
	Comment   string    `json:"comment"`
	CreatedAt time.Time `json:"created_at"`
}

type PostReaction struct {
	ReactionID int32     `json:"reaction_id"`
	PostID     int32     `json:"post_id"`
	MemberID   int32     `json:"member_id"`
	Reaction   string    `json:"reaction"`
	CreatedAt  time.Time `json:"created_at"`
}

type Streak struct {
	StreakID          int32        `json:"streak_id"`
	StreakSetID       int32        `json:"streak_set_id"`
	TotalStreakCount  int32        `json:"total_streak_count"`
	WeeklyStreakCount int32        `json:"weekly_streak_count"`
	Completed         bool         `json:"completed"`
	RecentDateAdded   sql.NullTime `json:"recent_date_added"`
	CreatedAt         time.Time    `json:"created_at"`
}

type StreakSet struct {
	StreakSetID int32     `json:"streak_set_id"`
	GroupID     int32     `json:"group_id"`
	MemberID    int32     `json:"member_id"`
	EndDate     time.Time `json:"end_date"`
	StartDate   time.Time `json:"start_date"`
}

type Tag struct {
	TagID      int32          `json:"tag_id"`
	TagName    string         `json:"tag_name"`
	IconUrl    sql.NullString `json:"icon_url"`
	CategoryID sql.NullInt32  `json:"category_id"`
}

type TagCategory struct {
	CategoryID   int32  `json:"category_id"`
	CategoryName string `json:"category_name"`
}
