name: ci-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'
      id: go

    - name: Checkout code into the Go module directory
      uses: actions/checkout@v3

    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/migrate
        which migrate

    - name: Compose DB Images
      run: docker compose -f docker-compose.db.yaml up -d --build

    - name: Make user migrations
      run: |
        docker exec user-db createdb --username=root --owner=root user_db
        migrate create -ext sql -dir pkg/database/postgres/userdb/migrations -seq init_user_schema